[card.frame-dragon]
id = 2608001
name = "Flame Dragon"
attribute = "Fire"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''If this card is destroyed by battle. Destroy a monster that have level 4 or lower'''
atk = 1000
def = 1000
ot = "CUSTOM"

[card.terra-dragon]
id = 2608002
name = "Terra Dragon"
attribute = "Earth"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''if this card is normal summon, add 1 monster card form your deck '''
atk = 1000
def = 1000
ot = "CUSTOM"

[card.wind-dragon]
id = 2608003
name = "Wind Dragon"
attribute = "Wind"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''If this card normal summon, destroy 1 spell/trap card'''
atk = 1000
def = 1000
ot = "CUSTOM"

[card.sea-dragon]
id = 2608004
name = "Sea Dragon"
attribute = "Water"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''if this card used at a sychro material, draw 1 card'''
atk = 1000
def = 1000
ot = "CUSTOM"

[card.dark-dragon]
id = 2608005
name = "Dark Dragon"
attribute = "Dark"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''if this card destroyed, destroy 1 dark monster'''
atk = 1000
def = 1000
ot = "CUSTOM"