[card.frame-dragon]
id = 2608001
name = "Flame Dragon"
attribute = "Fire"
level = 3
type = "monster effect tuner"
race = "dragon"
set = "dragon-city"
effect = '''if this card destroyed by a monster. Destroy a monster that have level 4 or lower'''
atk = 1000
def = 1000
ot = "CUSTOM"
